// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkGroupProsecutor.Server.Data.Context;

#nullable disable

namespace WorkGroupProsecutor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221116175424_withId")]
    partial class withId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Appeal.NoSolutionAppealModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("NoSolutionAppeal");
                });

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Appeal.RedirectedAppealModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("RedirectedAppeal");
                });

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Appeal.SatisfiedAppealModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantNotification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigationResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProsecutorAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightsRestoration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("SatisfiedAppeal");
                });

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Participants.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Appeal.NoSolutionAppealModel", b =>
                {
                    b.HasOne("WorkGroupProsecutor.Shared.Models.Participants.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Appeal.RedirectedAppealModel", b =>
                {
                    b.HasOne("WorkGroupProsecutor.Shared.Models.Participants.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WorkGroupProsecutor.Shared.Models.Appeal.SatisfiedAppealModel", b =>
                {
                    b.HasOne("WorkGroupProsecutor.Shared.Models.Participants.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
